org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.jetbrains.intellij.platform.intellijPlatformCache=G:/ProjectsDemo/tools/intellij-platform-cache/idea-inlay-hints-extension
org.jetbrains.intellij.platform.localPlatformArtifacts=G:/ProjectsDemo/tools/intellij-platform-local-artifacts/idea-inlay-hints-extension
